apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: polycomb
  annotations:
    project: polycomb
spec:
  template:
    metadata:
      name: polycomb
    spec:
      containers:
      - name: polycomb
        image: gcr.io/kellylab/polycomb
        command: ["bash", "scripts/script.sh"]
        resources:
          requests:
            memory: 500Mi
            cpu: 250m
      restartPolicy: Never
