apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: polycomb-XXX
  annotations:
    project: polycomb
spec:
  template:
    metadata:
      name: polycomb
    spec:
      containers:
      - name: polycomb
        image: gcr.io/kellylab/polycomb
        command: ["bash", "scripts/YYY.sh"]
        resources:
          requests:
            memory: 1000Mi
            cpu: 1000m
      restartPolicy: Never
