apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: polycomb-2020-70
  annotations:
    project: polycomb
spec:
  template:
    metadata:
      name: polycomb
    spec:
      containers:
      - name: polycomb
        image: gcr.io/kellylab/polycomb
        command: ["bash", "scripts/2020_70.sh"]
        resources:
          requests:
            memory: 2000Mi
            cpu: 1000m
      tolerations:
      - key: "persistent"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        persistent: "True"
      restartPolicy: Never
